### PR TITLE
Use Poetry for packages and create directory structure

### PR DESCRIPTION
**Pull request by Hoid**

### CODE REVIEW

**Review by pj-linebaugh — COMMENTED** [review]
I don't like the idea of having multiple copies of the same files.  Can the 'root' dir be added to the minimal-poetry-notebook image?  That or create another image in here that is used as the base for chip690, data720 and ordr-d.

**Comment by Hoid** [comment]
Do we _always_ want the same behavior for all three places with regards to the root directory? Like, what if in the future chip690 and data720 require some different permissions in the image than ordr-d and we need to add a new file in that directory called `root/helx/12-permissions.sh` or something, but just for data720 and chip690. We wouldn't be able to do that if we combined them into one place.

**Comment by pj-linebaugh** [comment]
For the situation you mentioned, if we create an image with the root dir in it using minimal-poetry-notebook as it's base (call it jupyter-helx-notebook-base), then we could have data720 and chip690 use jupyter-helx-notebook-base as their base image and add the 12-permissions.sh file to the image in their Dockerfile.

**Comment by Hoid** [comment]
Oh I see, you're saying we could have the main `root/helx` directory in the base image, which has the scripts that every child image will need, and each child image could add more scripts in a `root/helx` directory of their own, and copy that `root/helx` directory over at the beginning of the image build before running the scripts later on? If so I think I'm cool with that.

**Comment by pj-linebaugh** [comment]
Yes, exactly.  Having one Makefile at the top level to build all the images would be nice.  Could get a bit complicated.  Possibly have a top-level Makefile that calls Makefiles in the child image directories.  If the child Makefile is general enough could have one copy of it in the 'main' image directory and create symbolic links to it in the other image directories.

**Comment by Hoid** [comment]
Can I request that that stuff be done in a future PR? I'm almost done with modifying this one, I'll push soon.

**Review by pj-linebaugh — APPROVED** [review]

**Comment by pj-linebaugh** [comment]
sure.

**Comment by Hoid** [comment]
Also, I'm thinking of taking this line out
```
RUN fix-permissions "${CONDA_DIR}" && \
```
and just making that part this 
```
RUN fix-permissions "/home" && \
    chmod 664 /etc/group
```
That line above adds ~6GB to the image. What do you think? I would test it before pushing.

**Comment by Hoid** [comment]
Okay I tested the above, it seems to work fine. I was able to run the `fashion_mnist_stress_test.ipynb` file with no problem in helx-test.

**Pull request merged**
