### PR TITLE
Add jupyter-lab-professor

### PR DESCRIPTION
**Pull request by Hoid**
This PR adds jupyter-lab-professor as a project inside the jupyter-helx-notebook repo. I've tested building and pushing the image and everything works. The image is very small currently, around 5.44GB, but we haven't added the extension yet so it will balloon a bit once that happens.

### CODE REVIEW

**Comment by waTeim** [comment]
Ok, the very first question I have is, "is this appropriate for projects that that nothing to do with eduhelx?"  because the repo is generic.

**Comment by Hoid** [comment]
This repo just houses all of our jupyter notebook container projects across Helx, regardless of Eduhelx or not. And jupyter-lab-professor is definitely one of those, so I figured it fit here. If we have other eduhelx courses that need unique versions of jupyter lab they could be here too because they would be a "jupyter helx notebook".

**Comment by waTeim** [comment]
Ok got it, I see the subdirectories now.  Ok in that case.  You should probably also fix the other ones and put them in their own directories to avoid confusion maybe.  Or if in the case of the default (as well as the other ones make sure that those dockerfiles don't copy the other directories, I see maybe the beginnings in that.

Up until now, what's the one that we've been using?  This one or another, if another, better reconcile.

I'm not sure it's a good idea to have per-course dockerfiles (why would we need this, but see below).

I suggest, take out the kaniko references,  as it will never be used.

Remember; don't depend on the USER variable, this will almost certainly be overridden with a different number (ignored) in actual deployments -- especially on openshift.  Also, don't depend, be careful about home directories; same reason.

If you must, perhaps there's a section for each applicable project in the readme, but otherwise, I don't like calling them out by name.  But on the other hand, I suppose there can be specializations, in that case yes, maybe those should be pointed out.  For example, no one coming in from the internet will know what an "ordr(d)" is -- yea that's how it's spelled, this was a note in Wed's meeting.

**Review by pj-linebaugh — APPROVED** [review]

**Comment by Hoid** [comment]
Had a conversation with Jeff on Friday. We decided that it was okay to merge for now if we wanted, but that we need to fix this in a more permanent way asap, which I agree with wholeheartedly. That solution will likely involve mounting a configmap in jupyter lab pods using the user-mutator or something similar. Gonna merge this for now just to clean up this repo but I'll also make a task for getting this cleaned up.

**Pull request merged**
